#ifndef SP_TRANSFORMATION_HEADER
#define SP_TRANSFORMATION_HEADER

#include "OpenCLBase.cl"
#include "Vec3.cl"
#include "Quat.cl"

#define SP_TRANSFORMATION_ORIENTATION_OFFSET (0)
#define SP_TRANSFORMATION_POSITION_OFFSET (4)
#define SP_TRANSFORMATION_SCALE_OFFSET (7)
#define SP_TRANSFORMATION_STRIDER (10)


#endif // DOP18_OPENCL_HEADER