#ifndef SP_GAME_OBJECT_TYPE_HEADER
#define SP_GAME_OBJECT_TYPE_HEADER


#define SP_GAME_OBJECT_TYPE_NONE   0

#define SP_GAME_OBJECT_TYPE_CAMERA 1

#define SP_GAME_OBJECT_TYPE_END    2


#endif // SP_GAME_OBJECT_TYPE_HEADER